# Generated by Django 5.1 on 2024-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default=''),
        ),
    ]
